-- ==============================
-- USERS TABLE
-- ==============================

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ==============================
-- NOTES TABLE
-- ==============================

CREATE TABLE IF NOT EXISTS notes (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INT NOT NULL,

    title VARCHAR(200) NOT NULL,
    content TEXT,
    category VARCHAR(100),
    note_type VARCHAR(20) NOT NULL,
    is_pinned BOOLEAN DEFAULT FALSE,
    checklist_items TEXT,
    importance VARCHAR(20) DEFAULT 'MEDIUM',
    reminder_time TIMESTAMP NULL,
    reminder_enabled BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notes_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);


-- ==============================
-- DEMO USER
-- ==============================

INSERT INTO users (username, password)
SELECT 'demo', 'demo123'
WHERE NOT EXISTS (
    SELECT 1
    FROM users
    WHERE username = 'demo'
);


-- ==============================
-- DEMO NOTES
-- ==============================

INSERT INTO notes
(
    user_id,
    title,
    content,
    category,
    note_type,
    is_pinned,
    checklist_items,
    importance,
    reminder_time,
    reminder_enabled
)
SELECT
    user_id,
    'Welcome to NoteFlow',
    'This is your personal space for capturing ideas, planning work, and keeping your thoughts organized.',
    'Personal',
    'TEXT',
    TRUE,
    '[]',
    'HIGH',
    NULL,
    FALSE
FROM users
WHERE username = 'demo'
AND NOT EXISTS (
    SELECT 1
    FROM notes
    WHERE title = 'Welcome to NoteFlow'
);


INSERT INTO notes
(
    user_id,
    title,
    content,
    category,
    note_type,
    is_pinned,
    checklist_items,
    importance,
    reminder_time,
    reminder_enabled
)
SELECT
    user_id,
    'Java project roadmap',
    'Sketch the API endpoints, complete the data model, then prepare your final demo.',
    'College',
    'TEXT',
    FALSE,
    '[]',
    'MEDIUM',
    NULL,
    FALSE
FROM users
WHERE username = 'demo'
AND NOT EXISTS (
    SELECT 1
    FROM notes
    WHERE title = 'Java project roadmap'
);

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS importance VARCHAR(20) DEFAULT 'MEDIUM';

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS reminder_time TIMESTAMP NULL;

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN DEFAULT FALSE;