-- ==============================
-- USERS TABLE
-- ==============================

CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ==============================
-- NOTES TABLE
-- ==============================

CREATE TABLE IF NOT EXISTS notes (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INT NOT NULL,

    title VARCHAR(200) NOT NULL,
    content TEXT,
    category VARCHAR(100),
    note_type VARCHAR(20) NOT NULL,
    is_pinned BOOLEAN DEFAULT FALSE,
    checklist_items TEXT,

    importance VARCHAR(20) DEFAULT 'MEDIUM',
    reminder_time TIMESTAMP NULL,
    reminder_enabled BOOLEAN DEFAULT FALSE,
    reminder_sent BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notes_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- ==============================
-- EXISTING DATABASE MIGRATION
-- ==============================

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS importance VARCHAR(20) DEFAULT 'MEDIUM';

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS reminder_time TIMESTAMP NULL;

ALTER TABLE notes
ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN DEFAULT FALSE;

-- ==============================
-- PUSH SUBSCRIPTIONS TABLE
-- ==============================

CREATE TABLE IF NOT EXISTS push_subscriptions (
    subscription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id INT NOT NULL,

    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_push_subscription_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);


ALTER TABLE notes
ADD COLUMN IF NOT EXISTS reminder_sent BOOLEAN DEFAULT FALSE;